version: '3'

services:
  simulation:
    image: mysteriouscrawler/test
    ports:
      - "3000:3000"
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data 
volumes:
  postgres-data: